version: 2.1

workflows:
  build_plugin:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
    jobs:
      - build-plugin-wheel


jobs:
  build-plugin-wheel:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout      
      - setup_remote_docker:
          version: 20.10.2
      - run:
          name: setup_pants
          command: ./pants --version
      - run:
          name: Build package
          command: ./pants package pants_plugins/sendwave/pants_docker:pants-docker
      - save_cache:
          key: pants_cache-{{ arch }}
          paths:
            - $HOME/.cache/pants/setup
            - $HOME/.cache/pants/named_caches
            - $HOME/.cache/pants/lmdb_caches
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest
